## config/database.yml
# MySQL driver: gem install mysql2, include gem "mysql2" in Gemfile
# Use new-style password hashing: https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html

default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: protospace_42334_development

test:
  <<: *default
  database: protospace_42334_test

#---------------------------------------------------------
# Production: use DATABASE_URL (e.g., provided by Render)
#---------------------------------------------------------
production:
  url: <%= ENV["DATABASE_URL"] %>
